#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Munin plugins
MUNIN_PLUGINS="
	nginx
"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Setup gogs user and group"
groupadd -g 1100 gogs
useradd -m -s /usr/bin/false -d /home/gogs -u 1100 -g gogs gogs
passwd -N gogs
passwd -d gogs

echo "* Setup ssh dir"
mkdir -p /home/gogs/.ssh
chmod 0750 /home/gogs/.ssh
chown gogs:gogs /home/gogs/.ssh

echo "* Build gogs";
export GOPATH=/home/gogs/go
mkdir ${GOPATH}

npm install -g less
go get -u -tags "redis memcache cert" github.com/gogs/gogs
cd $GOPATH/src/github.com/gogs/gogs
go build
gopm update -v
gopm bin -u -v gogs -d /opt/local/bin

# Clean up
echo "* Cleaning up."
rm /root/customize
rm -rf /root/go

# Prepare image for provisioning
sm-prepare-image -y
